In [9]:
import uszipcode
from uszipcode import SearchEngine

import pandas as pd
city_data = pd.read_csv("sale_prices_city_sample.csv")
city_data

,RegionID,RegionName,StateName,SizeRank,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,6181,New York,New York,1,462700,466200,465600,469500,471300,468600,...,563200,570500,572800,569900,560800,571500,575100,571700,568300,573600
1,17426,Chicago,Illinois,4,188500,189400,186300,177700,167900,174700,...,271500,266500,264900,265000,264100,264300,270000,281400,302900,309200
2,18959,Las Vegas,Nevada,8,115600,114000,110800,109600,108200,107500,...,266000,268200,268400,270400,272200,274400,277500,278900,283000,284700
3,38128,Dallas,Texas,10,191900,184500,174500,152000,162900,171400,...,300600,301100,301500,310100,314600,316900,307100,321500,315500,321700
4,10920,Columbus,Ohio,19,89100,86000,79800,79300,78600,82300,...,152600,154800,158500,157700,162900,166600,172700,175300,173600,177600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,48710,Arnold,California,3704,266300,244200,217800,191200,201500,208400,...,326500,317800,293100,281000,279100,279400,287100,305300,325600,345100
1093,12306,Langhorne,Pennsylvania,3714,272300,291500,305600,342300,342600,329400,...,339800,371300,358600,366800,362400,396600,398200,404100,397100,416200
1094,33433,Pingree Grove,Illinois,3716,203600,175600,170200,184800,198900,191800,...,206200,198200,214700,211800,217500,250200,270300,260200,224300,216600
1095,32133,Idyllwild,California,3718,182900,225000,230500,240100,182500,183700,...,313500,309100,322400,321300,342400,330500,353800,355500,389300,360100
1096,50339,Sea Isle City,New Jersey,3722,500500,538200,543800,533600,552300,536300,...,718400,743300,762300,820300,783400,789700,776600,811700,815700,795900

In [10]:
# check to see if there are duplicate city names
city_names_pivot = city_data.pivot_table(columns=['RegionName'], aggfunc='size').sort_values(ascending=False)
city_duplicates_df = city_names_pivot.reset_index()
city_duplicates_df.head(66)

     RegionName  0
0   Springfield  4
1    Washington  3
2      Franklin  3
3     Westfield  3
4       Bristol  3
..          ... ..
61   Louisville  2
62      Medford  2
63     Richmond  2
64       Helena  2
65      Portage  2

[66 rows x 2 columns]

In [11]:
engine = SearchEngine()
zipcodes_dict = {"RegionID": [], "City": [], "State": [], "Zip Code": []}
bad_cities = {"RegionID": [], "City": [], "State": []}
for i in city_data.index:
    try:
        city=city_data['RegionName'].iloc[i]
        state=city_data['StateName'].iloc[i]
        regionId=city_data['RegionID'].iloc[i]
        zipcodes = engine.by_city_and_state(city=city, state=state)
    except:
        bad_cities["RegionID"].append(regionId)
        bad_cities["City"].append(city)
        bad_cities["State"].append(state)
        print(f"{city}, {state} not found")
        pass
    for zipcode in zipcodes:
        if regionId not in zipcodes_dict["RegionID"]:
            zipcodes_dict["RegionID"].append(regionId)
            zipcodes_dict["City"].append(city)
            zipcodes_dict['State'].append(state)
            zipcodes_dict['Zip Code'].append(zipcode.zipcode)
            print(zipcode.zipcode, zipcode.major_city)

10001 New York
60601 Chicago
89101 Las Vegas
75201 Dallas
43085 Columbus
40202 Louisville
32801 Orlando
80202 Denver
20001 Washington
97201 Portland
37201 Nashville
53202 Milwaukee
68102 Omaha
73102 Oklahoma City
27601 Raleigh
80902 Colorado Springs
55401 Minneapolis
70801 Baton Rouge
80010 Aurora
92801 Anaheim
27395 Greensboro
40502 Lexington
46802 Fort Wayne
55101 Saint Paul
34102 Naples
32301 Tallahassee
89002 Henderson
68502 Lincoln
99201 Spokane
32501 Pensacola
53703 Madison
92602 Irvine
89030 North Las Vegas
22201 Arlington
65802 Springfield
50307 Des Moines
22191 Woodbridge
32601 Gainesville
10701 Yonkers
60502 Aurora
28401 Wilmington
92646 Huntington Beach
97401 Eugene
34952 Port Saint Lucie
93901 Salinas
72201 Little Rock
47708 Evansville
66204 Overland Park
97301 Salem
97003 Beaverton
92025 Escondido
29401 Charleston
37127 Murfreesboro
91701 Rancho Cucamonga
22401 Fredericksburg
76541 Killeen
93550 Palmdale
37040 Clarksville
60540 Naperville
73003 Edmond
23075 Henrico
80722 Atwood
91766 Pomona
48103 Ann Arbor
94085 Sunnyvale
48906 Lansing
27511 Cary
65201 Columbia
75149 Mesquite
70001 Metairie
90501 Torrance
33755 Clearwater
90220 Compton
90301 Inglewood
66061 Olathe
80241 Thornton
80301 Boulder
75006 Carrollton
91360 Thousand Oaks
92392 Victorville
45011 Hamilton
77581 Pearland
62701 Springfield
18101 Allentown
92562 Murrieta
60431 Joliet
73026 Norman
83651 Nampa
80030 Westminster
93611 Clovis
94801 Richmond
80002 Arvada
22901 Charlottesville
35401 Tuscaloosa
91731 El Monte
93001 Ventura
75057 Lewisville
91790 West Covina
60120 Elgin
27834 Greenville
20109 Manassas
97123 Hillsboro
54301 Green Bay
75080 Richardson
19380 West Chester
90650 Norwalk
94509 Antioch
94533 Fairfield
98201 Everett
16501 Erie
33569 Riverview
95687 Vacaville
81501 Grand Junction
92344 Hesperia
94401 San Mateo
37064 Franklin
95340 Merced
29072 Lexington
27514 Chapel Hill
92376 Rialto
21044 Columbia
83642 Meridian
66044 Lawrence
Highlands Ranch, Colorado not found
66044 Lawrence
80631 Greeley
77573 League City
92691 Mission Viejo
94550 Livermore
23701 Portsmouth
90250 Hawthorne
37601 Johnson City
83401 Idaho Falls
28801 Asheville
21401 Annapolis
20164 Sterling
32703 Apopka
97501 Medford
75002 Allen
60544 Plainfield
02740 New Bedford
30075 Roswell
01901 Lynn
37311 Cleveland
23185 Williamsburg
64063 Lees Summit
30263 Newnan
48187 Canton
20170 Herndon
86001 Flagstaff
91708 Chino
34945 Fort Pierce
02720 Fall River
92660 Newport Beach
60085 Waukegan
78660 Pflugerville
55796 Winton
80501 Longmont
07011 Clifton
38301 Jackson
99201 Spokane
97030 Gresham
48083 Troy
37660 Kingsport
02169 Quincy
84401 Ogden
22554 Stafford
95336 Manteca
93010 Camarillo
48331 Farmington
92307 Apple Valley
32765 Oviedo
29464 Mount Pleasant
91722 Covina
91784 Upland
32725 Deltona
90745 Carson
17601 Lancaster
55007 Brook Park
94040 Mountain View
27502 Apex
77459 Missouri City
77406 Richmond
99301 Pasco
85122 Casa Grande
94582 San Ramon
12601 Poughkeepsie
Plymouth, Minnesota not found
12601 Poughkeepsie
18015 Bethlehem
Cheektowaga, New York not found
18015 Bethlehem
39042 Brandon
92630 Lake Forest
10801 New Rochelle
34683 Palm Harbor
48033 Southfield
28115 Mooresville
91709 Chino Hills
08723 Brick
92530 Lake Elsinore
30024 Suwanee
23059 Glen Allen
75022 Flower Mound
48327 Waterford
47201 Columbus
47906 West Lafayette
92886 Yorba Linda
84040 Layton
60440 Bolingbrook
48197 Ypsilanti
34769 Saint Cloud
33410 Palm Beach Gardens
94501 Alameda
34285 Venice
32922 Cocoa
94301 Palo Alto
21801 Salisbury
32570 Milton
97526 Grants Pass
70062 Kenner
55311 Maple Grove
97330 Corvallis
32162 The Villages
Eagan, Minnesota not found
32162 The Villages
60462 Orland Park
93401 San Luis Obispo
76180 North Richland Hills
96706 Ewa Beach
30214 Fayetteville
90660 Pico Rivera
48640 Midland
37075 Hendersonville
55044 Lakeville
33543 Wesley Chapel
33594 Valrico
92677 Laguna Niguel
91770 Rosemead
54601 La Crosse
44256 Medina
20190 Reston
66203 Shawnee
89701 Carson City
90640 Montebello
56301 Saint Cloud
55344 Eden Prairie
92672 San Clemente
80020 Broomfield
56572 Pelican Rapids
56011 Belle Plaine
21122 Pasadena
32127 Port Orange
90631 La Habra
55306 Burnsville
34637 Land O Lakes
91754 Monterey Park
97321 Albany
50265 West Des Moines
13501 Utica
95020 Gilroy
43130 Lancaster
45069 West Chester
06010 Bristol
37087 Lebanon
91702 Azusa
90247 Gardena
22003 Annandale
60076 Skokie
95014 Cupertino
25401 Martinsburg
28078 Huntersville
48067 Royal Oak
63376 Saint Peters
54901 Oshkosh
30458 Statesboro
33122 Miami
60187 Wheaton
06040 Manchester
48843 Howell
15601 Greensburg
Bartlett, Tennessee not found
15601 Greensburg
07083 Union
70053 Gretna
08854 Piscataway
60515 Downers Grove
92708 Fountain Valley
46526 Goshen
44276 Sterling
60402 Berwyn
92324 Colton
46307 Crown Point
73852 Mooreland
60025 Glenview
01013 Chicopee
85138 Maricopa
08527 Jackson
30052 Loganville
59601 Helena
07470 Wayne
43701 Zanesville
02188 Weymouth
20151 Chantilly
22101 Mc Lean
32547 Fort Walton Beach
37813 Morristown
30240 Lagrange
76039 Euless
99352 Richland
48374 Novi
91740 Glendora
94506 Danville
34737 Howey In The Hills
34134 Bonita Springs
32750 Longwood
93215 Delano
94546 Castro Valley
14075 Hamburg
59901 Kalispell
91745 Hacienda Heights
85326 Buckeye
66215 Lenexa
23832 Chesterfield
07030 Hoboken
75115 Desoto
92399 Yucaipa
70433 Covington
38555 Crossville
37167 Smyrna
34711 Clermont
61761 Normal
60148 Lombard
Kentwood, Michigan not found
60148 Lombard
19054 Levittown
30019 Dacula
60477 Tinley Park
50021 Ankeny
06497 Stratford
92870 Placentia
95023 Hollister
71291 West Monroe
70072 Marrero
27529 Garner
55329 Eden Valley
06108 East Hartford
80022 Commerce City
96734 Kailua
20814 Bethesda
75165 Waxahachie
92262 Palm Springs
75068 Little Elm
90638 La Mirada
90630 Cypress
37122 Mount Juliet
90703 Cerritos
95658 Newcastle
92656 Aliso Viejo
Milwaukie, Oregon not found
92656 Aliso Viejo
75104 Cedar Hill
60169 Hoffman Estates
96744 Kaneohe
94568 Dublin
97470 Roseburg
74017 Claremore
47025 Lawrenceburg
49002 Portage
Murray, Utah not found
49002 Portage
80120 Littleton
27284 Kernersville
75088 Rowlett
70401 Hammond
55007 Brook Park
54982 Wautoma
07003 Bloomfield
38017 Collierville
48066 Roseville
14850 Ithaca
55345 Minnetonka
60126 Elmhurst
Dunwoody, Georgia not found
60126 Elmhurst
48114 Brighton
31313 Hinesville
44060 Mentor
60115 Dekalb
08816 East Brunswick
75098 Wylie
96707 Kapolei
30809 Evans
96720 Hilo
Evesham Township, New Jersey not found
96720 Hilo
77449 Katy
27526 Fuquay Varina
23690 Yorktown
55379 Shakopee
14586 West Henrietta
08807 Bridgewater
45613 Beaver
27360 Thomasville
70448 Mandeville
61265 Moline
02474 Arlington
40324 Georgetown
02630 Barnstable
11772 Patchogue
91748 Rowland Heights
86314 Prescott Valley
45014 Fairfield
22015 Burke
02703 Attleboro
94560 Newark
40356 Nicholasville
11757 Lindenhurst
34737 Howey In The Hills
01201 Pittsfield
28560 New Bern
91016 Monrovia
70769 Prairieville
37027 Brentwood
03301 Concord
63005 Chesterfield
97034 Lake Oswego
11801 Hicksville
32746 Lake Mary
28376 Raeford
32955 Rockledge
60188 Carol Stream
76244 Keller
07032 Kearny
60012 Crystal Lake
08054 Mount Laurel
37743 Greeneville
63026 Fenton
07036 Linden
01085 Westfield
50322 Urbandale
13088 Liverpool
48167 Northville
08902 North Brunswick
60101 Addison
70737 Gonzales
01453 Leominster
07416 Franklin
93446 Paso Robles
63011 Ballwin
91744 La Puente
07746 Marlboro
96701 Aiea
07666 Teaneck
11003 Elmont
53005 Brookfield
85351 Sun City
60107 Streamwood
90275 Rancho Palos Verdes
60060 Mundelein
53146 New Berlin
20735 Clinton
32707 Casselberry
38138 Germantown
60103 Bartlett
84660 Spanish Fork
37620 Bristol
84065 Riverton
11704 West Babylon
76513 Belton
01801 Woburn
80601 Brighton
94561 Oakley
68046 Papillion
21236 Nottingham
63385 Wentzville
12866 Saratoga Springs
30736 Ringgold
52302 Marion
45342 Miamisburg
92253 La Quinta
91763 Montclair
94044 Pacifica
24153 Salem
60068 Park Ridge
63010 Arnold
48170 Plymouth
34761 Ocoee
43551 Perrysburg
76053 Hurst
80110 Englewood
Northglenn, Colorado not found
80110 Englewood
19709 Middletown
53531 Deerfield
35473 Northport
44814 Berlin Heights
02184 Braintree
20747 District Heights
97128 Mcminnville
84067 Roy
06611 Trumbull
91711 Claremont

91001 Altadena
11554 East Meadow
50613 Cedar Falls
21784 Sykesville
07676 Township Of Washington
30813 Grovetown
53051 Menomonee Falls
92675 San Juan Capistrano
55355 Litchfield
46123 Avon
92595 Wildomar
64780 Rockville
18301 East Stroudsburg
Boardman, Ohio not found
18301 East Stroudsburg
93060 Santa Paula
97756 Redmond
91780 Temple City
56284 Renville
40391 Winchester
48382 Commerce Township
37086 La Vergne
45103 Batavia
45373 Troy
01810 Andover
55016 Cottage Grove
37160 Shelbyville
21136 Reisterstown
43147 Pickerington
95030 Los Gatos
92311 Barstow
53154 Oak Creek
22079 Lorton
21740 Hagerstown
45814 Arlington
94523 Pleasant Hill
43065 Powell
46368 Portage
95901 Marysville
39110 Madison
55076 Inver Grove Heights
02368 Randolph
90266 Manhattan Beach
02472 Watertown
21144 Severn
66206 Leawood
30542 Flowery Branch
92301 Adelanto
34688 Tarpon Springs
81301 Durango
22551 Spotsylvania
93561 Tehachapi
81401 Montrose
02420 Lexington
20155 Gainesville
43560 Sylvania
Ken Caryl, Colorado not found
43560 Sylvania
02038 Franklin
Cottonwood Heights, Utah not found
02038 Franklin
48178 South Lyon
13440 Rome
21113 Odenton
60174 Saint Charles
48021 Eastpointe
29063 Irmo
21133 Randallstown
44039 North Ridgeville
21075 Elkridge
11510 Baldwin
28104 Matthews
72120 Sherwood
55372 Prior Lake
55318 Chaska
53090 West Bend
93422 Atascadero
15102 Bethel Park
07753 Neptune
98467 University Place
95070 Saratoga
39208 Pearl
28607 Boone
55304 Andover
28348 Hope Mills
16652 Huntingdon
77536 Deer Park
44070 North Olmsted
60714 Niles
22980 Waynesboro
Security-Widefield, Colorado not found
27302 Mebane
35007 Alabaster
35593 Vina
94010 Burlingame
21234 Parkville
14120 North Tonawanda
46074 Westfield
48383 White Lake
03820 Dover
78108 Cibolo
34748 Leesburg
93940 Monterey
21009 Abingdon
22630 Front Royal
07090 Westfield
72015 Benton
44281 Wadsworth
01845 North Andover
80033 Wheat Ridge
20772 Upper Marlboro
01876 Tewksbury
39564 Ocean Springs
Des Moines, Washington not found
39564 Ocean Springs
02492 Needham
34450 Inverness
78640 Kyle
20186 Warrenton
19026 Drexel Hill
97068 West Linn
93662 Selma
49464 Zeeland
27012 Clemmons
65721 Ozark
94070 San Carlos
13039 Cicero
76092 Southlake
64068 Liberty
20740 College Park
70068 La Place
49028 Bronson
46530 Granger
56401 Brainerd
97838 Hermiston
65714 Nixa
16066 Cranberry Township
48195 Southgate
40065 Shelbyville
11720 Centereach
93420 Arroyo Grande
60048 Libertyville
06066 Vernon Rockville
02919 Johnston
34690 Holiday
37659 Jonesborough
97140 Sherwood
96150 South Lake Tahoe
60134 Geneva
06512 East Haven
64659 Meadville
85340 Litchfield Park
97132 Newberg
49341 Rockford
68701 Norfolk
84074 Tooele
20705 Beltsville
92860 Norco
21771 Mount Airy
97086 Happy Valley
07110 Nutley
01757 Milford
56045 Hollandale
34990 Palm City
48867 Owosso
01060 Northampton
95961 Olivehurst
02072 Stoughton
97502 Central Point
23834 Colonial Heights
76548 Harker Heights
32533 Cantonment
15146 Monroeville
30746 Sugar Valley
96732 Kahului
90680 Stanton
40004 Bardstown
80817 Fountain
98370 Poulsbo
02186 Milton
48101 Allen Park
55731 Ely
01923 Danvers
94585 Suisun City
02176 Melrose
28785 Waynesville
92694 Ladera Ranch
27540 Holly Springs
13104 Manlius
Fitchburg, Wisconsin not found
13104 Manlius
21146 Severna Park
98382 Sequim
11763 Medford
37172 Springfield
07652 Paramus
84044 Magna
60156 Lake In The Hills
64093 Warrensburg
97062 Tualatin
37055 Dickson
97071 Woodburn
07430 Mahwah
55024 Farmington
36535 Foley
60142 Huntley
77532 Crosby
49428 Jenison
97116 Forest Grove
01880 Wakefield
64443 Easton
32578 Niceville
Shoreview, Minnesota not found
32578 Niceville
28734 Franklin
22025 Dumfries
43537 Maumee
32132 Edgewater
60091 Wilmette
23139 Powhatan
63755 Jackson
27560 Morrisville
35125 Pell City
28031 Cornelius
32789 Winter Park
91945 Lemon Grove
07480 West Milford
21627 Crocheron
81212 Canon City
94510 Benicia
11784 Selden
03054 Merrimack
28658 Newton
47933 Crawfordsville
80401 Golden
35752 Hollywood
07450 Ridgewood
37355 Manchester
86326 Cottonwood
80439 Evergreen
37771 Lenoir City
54956 Neenah
84054 North Salt Lake
24551 Forest
34491 Summerfield
97520 Ashland
70791 Zachary
32566 Navarre
43004 Blacklick
48864 Okemos
19454 North Wales
40403 Berea
02081 Walpole
03051 Hudson
53108 Caledonia
24557 Gretna
Columbine, Colorado not found
24557 Gretna
54650 Onalaska
60510 Batavia
48380 Milford
17201 Chambersburg
31324 Richmond Hill
20855 Derwood
97420 Coos Bay
48094 Washington
98040 Mercer Island
49459 Walkerville
94530 El Cerrito
Carney, Maryland not found
94530 El Cerrito
19064 Springfield
32043 Green Cove Springs
Vinings, Georgia not found
32043 Green Cove Springs
84005 Eagle Mountain
92118 Coronado
63052 Imperial
60053 Morton Grove
21601 Easton
61571 Washington
36526 Daphne
37388 Tullahoma
60439 Lemont
30528 Cleveland
17522 Ephrata
20659 Mechanicsville
60050 Mchenry
28572 Pink Hill
15090 Wexford
37865 Seymour
55309 Big Lake
20169 Haymarket
92780 Tustin
37148 Portland
21114 Crofton
08055 Medford
91302 Calabasas
55316 Champlin
93041 Port Hueneme
55068 Rosemount
95620 Dixon
41005 Burlington
91384 Castaic
20832 Olney
73064 Mustang
32763 Orange City
Anthem, Arizona not found
32763 Orange City
60178 Sycamore
46158 Mooresville
60441 Lockport
55317 Chanhassen
04106 South Portland
89410 Gardnerville
02021 Canton
13630 De Kalb Junction
80132 Monument
23061 Gloucester
49315 Byron Center
60561 Darien
11530 Garden City
40031 La Grange
77586 Seabrook
06437 Guilford
44138 Olmsted Falls
31558 Saint Marys
44236 Hudson
29045 Elgin
56073 New Ulm
64012 Belton
98028 Kenmore
29316 Boiling Springs
63043 Maryland Heights
92082 Valley Center
60181 Villa Park
48176 Saline
29016 Blythewood
98671 Washougal
08869 Raritan
97070 Wilsonville
92371 Phelan
90745 Carson
29142 Santee
72113 Maumelle
75189 Royse City
37934 Farragut
91008 Duarte
92354 Loma Linda
28532 Havelock
94547 Hercules
08091 West Berlin
03110 Bedford
74037 Jenks
03801 Portsmouth
25414 Charles Town
33573 Sun City Center
84306 Collinston
84075 Syracuse
Mountain Brook, Alabama not found
84075 Syracuse
83634 Kuna
60131 Franklin Park
21012 Arnold
43110 Canal Winchester
55329 Eden Valley
21037 Edgewater
47546 Jasper
33852 Lake Placid
20646 La Plata
56089 Twin Lakes
37178 Tennessee Ridge
55075 South Saint Paul
07871 Sparta
80026 Lafayette
33040 Key West
48820 Dewitt
48169 Pinckney
70785 Walker
30512 Blairsville
21811 Berlin
41091 Union
44137 Maple Heights
06840 New Canaan
40014 Crestwood
Corinth, Texas not found
40014 Crestwood
75048 Sachse
35124 Pelham
07730 Hazlet
49855 Marquette
98043 Mountlake Terrace
93023 Ojai
78148 Universal City
53172 South Milwaukee
31326 Rincon
65606 Alton
14806 Andover
46706 Auburn
41018 Erlanger
20706 Lanham
31005 Bonaire
02536 East Falmouth
07960 Morristown
27591 Wendell
87544 Los Alamos
17225 Greencastle
93444 Nipomo
43616 Oregon
50125 Indianola
91214 La Crescenta
80027 Louisville
08028 Glassboro
60513 Brookfield
44116 Rocky River
60805 Evergreen Park
22124 Oakton
30277 Sharpsburg
65738 Republic
17013 Carlisle
32778 Tavares
44137 Maple Heights
44142 Brookpark
94564 Pinole
44017 Berea
76437 Cisco
73008 Bethany
31548 Kingsland
04330 Augusta
17070 New Cumberland
31008 Byron
19958 Lewes
04072 Saco
48433 Flushing
20657 Lusby
94563 Orinda
Sherrelwood, Colorado not found
94563 Orinda
61611 East Peoria
22963 Palmyra
50009 Altoona
17866 Coal Township
21050 Forest Hill
80516 Erie
78635 Hye
07067 Colonia
22066 Great Falls
74021 Collinsville
46774 New Haven
12061 East Greenbush
Tinton Falls, New Jersey not found
12061 East Greenbush
50263 Waukee
80831 Peyton
01950 Newburyport
Bon Air, Virginia not found
24281 Rose Hill
32561 Gulf Breeze
30677 Watkinsville
18847 Susquehanna
37862 Sevierville
63548 Lancaster
46122 Danville
94507 Alamo
20895 Kensington
19014 Aston
84401 Ogden
97103 Astoria
16001 Butler
50131 Johnston
91902 Bonita
49331 Lowell
11733 East Setauket
35080 Helena
Delran Township, New Jersey not found
35080 Helena
41048 Hebron
30548 Hoschton
33534 Gibsonton
27592 Willow Spring
84045 Saratoga Springs
02351 Abington
46140 Greenfield
Texas, Michigan not found
46140 Greenfield
48356 Highland
38016 Cordova
63367 Lake Saint Louis
29585 Pawleys Island
32937 Satellite Beach
08012 Blackwood
84651 Payson
44470 Southington
80550 Windsor

44720 North Canton
34275 Nokomis
96022 Cottonwood
77619 Groves
93950 Pacific Grove
81521 Fruita
32541 Destin
84401 Ogden
85087 New River
55918 Brownsdale
85253 Paradise Valley
37341 Harrison
20105 Aldie
22508 Locust Grove
27596 Youngsville
02806 Barrington
Lyndhurst, Ohio not found
02806 Barrington
29369 Moore
19425 Chester Springs
Middle Valley, Tennessee not found
19425 Chester Springs
94517 Clayton
48118 Chelsea
19320 Coatesville
43054 New Albany
76036 Crowley
37150 Red Boiling Springs
80863 Woodland Park
70447 Madisonville
33801 Lakeland
55101 Saint Paul
48017 Clawson
Lakeside, Virginia not found
48017 Clawson
37073 Greenbrier
21903 Perryville
98065 Snoqualmie
92075 Solana Beach
92314 Big Bear City
97355 Lebanon
28374 Pinehurst
95451 Kelseyville
Crestwood, Missouri not found
95451 Kelseyville
35071 Gardendale
49684 Traverse City
Country Walk, Florida not found
49684 Traverse City
19335 Downingtown
19428 Conshohocken
30620 Bethlehem
64089 Smithville
33455 Hobe Sound
96019 Shasta Lake
78873 Leakey
07840 Hackettstown
85118 Gold Canyon
89423 Minden
33480 Palm Beach
64029 Grain Valley
08096 Woodbury
07950 Morris Plains
37377 Signal Mountain
03818 Conway
72719 Centerton
38060 Oakland
19007 Bristol
07928 Chatham
17050 Mechanicsburg
32951 Melbourne Beach
18951 Quakertown
28613 Conover
39525 Diamondhead
08879 South Amboy
19067 Morrisville
32569 Mary Esther
80549 Wellington
33947 Rotonda West
07921 Bedminster
93546 Mammoth Lakes
55362 Monticello
08203 Brigantine
17011 Camp Hill
89067 Coyote Springs
Williamsburg, Florida not found
33931 Fort Myers Beach
17356 Red Lion
80421 Bailey
30549 Jefferson
80517 Estes Park
19053 Feasterville Trevose
75409 Anna
19002 Ambler
80534 Johnstown
18055 Hellertown
32003 Fleming Island
15108 Coraopolis
Timber Pines, Florida not found
19426 Collegeville
15017 Bridgeville
33957 Sanibel
95467 Hidden Valley Lake
19468 Royersford
08260 Wildwood
32550 Miramar Beach
96738 Waikoloa
76262 Roanoke
85641 Vail
34228 Longboat Key
18938 New Hope
95223 Arnold
19047 Langhorne
60081 Spring Grove
08243 Sea Isle City

In [12]:
bad_cities

{'RegionID': [38992,
  26561,
  37840,
  17845,
  10264,
  25383,
  12751,
  6102,
  49352,
  51952,
  26213,
  3731,
  119842,
  14825,
  396536,
  24372,
  11441,
  54410,
  119404,
  157222,
  396606,
  3418,
  26027,
  51547,
  120381,
  54702,
  35084,
  11083,
  397390,
  8823,
  228223,
  32403,
  29879,
  124049,
  126662,
  126414],
 'City': ['Highlands Ranch',
  'Plymouth',
  'Cheektowaga',
  'Eagan',
  'Bartlett',
  'Kentwood',
  'Milwaukie',
  'Murray',
  'Dunwoody',
  'Evesham Township',
  'Northglenn',
  'Boardman',
  'Ken Caryl',
  'Cottonwood Heights',
  'Security-Widefield',
  'Des Moines',
  'Fitchburg',
  'Shoreview',
  'Columbine',
  'Carney',
  'Vinings',
  'Anthem',
  'Mountain Brook',
  'Corinth',
  'Sherrelwood',
  'Tinton Falls',
  'Bon Air',
  'Delran Township',
  'Texas',
  'Lyndhurst',
  'Middle Valley',
  'Lakeside',
  'Crestwood',
  'Country Walk',
  'Williamsburg',
  'Timber Pines'],
 'State': ['Colorado',
  'Minnesota',
  'New York',
  'Minnesota',
  'Tennessee',
  'Michigan',
  'Oregon',
  'Utah',
  'Georgia',
  'New Jersey',
  'Colorado',
  'Ohio',
  'Colorado',
  'Utah',
  'Colorado',
  'Washington',
  'Wisconsin',
  'Minnesota',
  'Colorado',
  'Maryland',
  'Georgia',
  'Arizona',
  'Alabama',
  'Texas',
  'Colorado',
  'New Jersey',
  'Virginia',
  'New Jersey',
  'Michigan',
  'Ohio',
  'Tennessee',
  'Virginia',
  'Missouri',
  'Florida',
  'Florida',
  'Florida']}

In [13]:
bad_cities_df = pd.DataFrame(bad_cities, columns=["RegionID", "City", "State"])
bad_cities_df

    RegionID                City       State
0      38992     Highlands Ranch    Colorado
1      26561            Plymouth   Minnesota
2      37840         Cheektowaga    New York
3      17845               Eagan   Minnesota
4      10264            Bartlett   Tennessee
5      25383            Kentwood    Michigan
6      12751           Milwaukie      Oregon
7       6102              Murray        Utah
8      49352            Dunwoody     Georgia
9      51952    Evesham Township  New Jersey
10     26213          Northglenn    Colorado
11      3731            Boardman        Ohio
12    119842           Ken Caryl    Colorado
13     14825  Cottonwood Heights        Utah
14    396536  Security-Widefield    Colorado
15     24372          Des Moines  Washington
16     11441           Fitchburg   Wisconsin
17     54410           Shoreview   Minnesota
18    119404           Columbine    Colorado
19    157222              Carney    Maryland
20    396606             Vinings     Georgia
21      3418              Anthem     Arizona
22     26027      Mountain Brook     Alabama
23     51547             Corinth       Texas
24    120381         Sherrelwood    Colorado
25     54702        Tinton Falls  New Jersey
26     35084             Bon Air    Virginia
27     11083     Delran Township  New Jersey
28    397390               Texas    Michigan
29      8823           Lyndhurst        Ohio
30    228223       Middle Valley   Tennessee
31     32403            Lakeside    Virginia
32     29879           Crestwood    Missouri
33    124049        Country Walk     Florida
34    126662        Williamsburg     Florida
35    126414        Timber Pines     Florida

In [14]:
bad_cities_df.to_csv("bad_cities.csv", index=False)

In [15]:
zipcodes_df = pd.DataFrame(zipcodes_dict, columns=['RegionID', 'City', 'State', 'Zip Code'])
zipcodes_df

      RegionID           City         State Zip Code
0         6181       New York      New York    10001
1        17426        Chicago      Illinois    60601
2        18959      Las Vegas        Nevada    89101
3        38128         Dallas         Texas    75201
4        10920       Columbus          Ohio    43085
...        ...            ...           ...      ...
1071     49592       New Hope  Pennsylvania    18938
1072     48710         Arnold    California    95223
1073     12306      Langhorne  Pennsylvania    19047
1074     33433  Pingree Grove      Illinois    60081
1075     50339  Sea Isle City    New Jersey    08243

[1076 rows x 4 columns]

In [17]:
zipcodes_df.to_csv("zipcodes.csv", index=False)