In [1]:
import uszipcode
from uszipcode import SearchEngine
import geopy
from geopy.geocoders import Nominatim
import pandas as pd
import os
import csv
from pathlib import Path
import datetime as dt

C:\Users\corpo\anaconda3\envs\mlenv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
# load zip code dictionary created in previous file
zipcode_file = Path('./resources/zipcodes.csv')
zipcodes_df = pd.read_csv(zipcode_file)
zipcodes_df

      RegionID           City         State  Zip Code
0         6181       New York      New York     10001
1        17426        Chicago      Illinois     60601
2        18959      Las Vegas        Nevada     89101
3        38128         Dallas         Texas     75201
4        10920       Columbus          Ohio     43085
...        ...            ...           ...       ...
1030     49592       New Hope  Pennsylvania     18938
1031     48710         Arnold    California     95223
1032     12306      Langhorne  Pennsylvania     19047
1033     33433  Pingree Grove      Illinois     60081
1034     50339  Sea Isle City    New Jersey      8243

[1035 rows x 4 columns]

## CREATE GEOCODING API SEARCH TO ADD COORDINATE DATA

### We'll use the Nominatim API through GeoPy

In [ ]:
# Create empty dictionaries to store our results
zipcodes_coords_dict = {"RegionID": [], "City": [], "State": [], "Zip Code": [], "Latitude": [], "Longitude": []}
bad_coords = {"RegionID": [], "City": [], "State": [], "Zip Code": []}
geolocator = Nominatim(user_agent="coords_locator")
for i in zipcodes_df.index:
    try:
        country= "United States"
        place = zipcodes_df["Zip Code"].iloc[i]
        city=zipcodes_df['City'].iloc[i]
        state=zipcodes_df['State'].iloc[i]
        regionId=zipcodes_df['RegionID'].iloc[i]
        location = geolocator.geocode({"postalcode": place, "country": country})
        for loc in location:
            if regionId not in zipcodes_coords_dict["RegionID"]:
                zipcodes_coords_dict['RegionID'].append(regionId)
                zipcodes_coords_dict['City'].append(city)
                zipcodes_coords_dict['State'].append(state)
                zipcodes_coords_dict['Zip Code'].append(place)
                zipcodes_coords_dict['Latitude'].append(location.latitude)
                zipcodes_coords_dict['Longitude'].append(location.longitude)
                print((int(i)+1, city, state, location.latitude, location.longitude))
    except:
        # Add locations with errors to separate dictionary
        bad_coords['RegionID'].append(regionId)
        bad_coords['City'].append(city)
        bad_coords['State'].append(state)
        bad_coords['Zip Code'].append(place)
        print(f"--------No coords found for {city}, {state}--------")
        pass

(1, 'New York', 'New York', 40.74841846379893, -73.99414662538305)
(2, 'Chicago', 'Illinois', 41.88590973888887, -87.62384881079517)
(3, 'Las Vegas', 'Nevada', 36.16754012512261, -115.1397390708225)
(4, 'Dallas', 'Texas', 32.78591838122747, -96.79898740986125)
(5, 'Columbus', 'Ohio', 40.09937865821035, -83.01535635988175)
(6, 'Louisville', 'Kentucky', 38.251258306496524, -85.74953130976665)
(7, 'Orlando', 'Florida', 28.54369969285714, -81.37867734893716)
(8, 'Denver', 'Colorado', 39.75047244283387, -104.99667202434155)
(9, 'Washington', 'District of Columbia', 38.91577904545211, -77.01780075676825)
(10, 'Portland', 'Oregon', 45.50849526040868, -122.6927202533267)
(11, 'Nashville', 'Tennessee', 36.1649490471154, -86.7749866054015)
(12, 'Milwaukee', 'Wisconsin', 43.04878110657971, -87.89918243948371)
(13, 'Omaha', 'Nebraska', 41.26096203127026, -95.93490843192167)
(14, 'Oklahoma City', 'Oklahoma', 35.45077612039714, -97.51630135887922)
(15, 'Raleigh', 'North Carolina', 35.77569627187468, -78.63620578646977)
(16, 'Colorado Springs', 'Colorado', 38.75690697619047, -104.80612063249079)
(17, 'Minneapolis', 'Minnesota', 44.98030381092867, -93.27195897032745)
(18, 'Baton Rouge', 'Louisiana', 30.44967257142857, -91.18825912308387)
(19, 'Aurora', 'Colorado', 39.747654686292734, -104.86042991143192)
(20, 'Anaheim', 'California', 33.84972059565739, -117.94287382078076)
--------No coords found for Greensboro, North Carolina--------
(22, 'Lexington', 'Kentucky', 38.019129545617815, -84.4872850949603)
(23, 'Fort Wayne', 'Indiana', 41.06941290557671, -85.15706869439919)
(24, 'Saint Paul', 'Minnesota', 44.95626671213007, -93.08780471264137)
(25, 'Naples', 'Florida', 26.147321411228212, -81.79731580645046)
(26, 'Tallahassee', 'Florida', 30.435668599187384, -84.26374190271257)
(27, 'Henderson', 'Nevada', 35.99861716333332, -114.94898312948244)
(28, 'Lincoln', 'Nebraska', 40.785386564241826, -96.6933521262175)
(29, 'Spokane', 'Washington', 47.66132581586539, -117.42909429783734)
(30, 'Pensacola', 'Florida', 30.42023855692076, -87.22529853888044)
(31, 'Madison', 'Wisconsin', 43.076431796775175, -89.38113091889922)
(32, 'Irvine', 'California', 33.732597346693105, -117.77182782601952)
(33, 'North Las Vegas', 'Nevada', 36.21915111065573, -115.10964668905407)
(34, 'Arlington', 'Virginia', 38.886106852469396, -77.10087405524759)
(35, 'Springfield', 'Missouri', 37.21147456810666, -93.30666755935674)
--------No coords found for Des Moines, Iowa--------
(37, 'Woodbridge', 'Virginia', 38.64481239929794, -77.2571280313322)
(38, 'Gainesville', 'Florida', 29.648850667246183, -82.32637849613738)
(39, 'Yonkers', 'New York', 40.94329052192868, -73.88601984537547)
(40, 'Aurora', 'Illinois', 41.79098534391594, -88.25875979931293)
(41, 'Wilmington', 'North Carolina', 34.234318467582426, -77.94055099514162)
(42, 'Huntington Beach', 'California', 33.66822076890284, -117.96789772829062)
(43, 'Eugene', 'Oregon', 44.052062913754305, -123.08546682624394)
(44, 'Port Saint Lucie', 'Florida', 27.29204376611316, -80.29780764669377)
(45, 'Salinas', 'California', 36.668259592836215, -121.64553152842092)
(46, 'Little Rock', 'Arkansas', 34.74927843521142, -92.28525841302428)
(47, 'Evansville', 'Indiana', 37.973866151315775, -87.57247620424651)
(48, 'Overland Park', 'Kansas', 38.988495015807175, -94.67505408761436)
(49, 'Salem', 'Oregon', 44.93962618067226, -123.0116011857025)
(50, 'Beaverton', 'Oregon', 45.50526595610471, -122.877088659611)
(51, 'Escondido', 'California', 33.10664496940168, -117.06877273536956)
(52, 'Charleston', 'South Carolina', 32.78139419407751, -79.93464017881699)
(53, 'Murfreesboro', 'Tennessee', 35.784870910687005, -86.36010513420153)
(54, 'Rancho Cucamonga', 'California', 34.1391631354867, -117.6120480161814)
(55, 'Fredericksburg', 'Virginia', 38.299406023686096, -77.47703384212096)
(56, 'Killeen', 'Texas', 31.115535147786456, -97.72986731716418)
(57, 'Palmdale', 'California', 34.57244974666666, -118.08200349916497)
(58, 'Clarksville', 'Tennessee', 36.54933500786588, -87.34592775678533)
(59, 'Naperville', 'Illinois', 41.76742323749516, -88.16165021194273)
(60, 'Edmond', 'Oklahoma', 35.63897519881754, -97.53815966412911)
(61, 'Henrico', 'Virginia', 37.543176267095554, -77.32243779177045)
(62, 'Lakewood', 'Colorado', 40.5380739725627, -103.27248704962)
(63, 'Pomona', 'California', 34.04074011893167, -117.7518241291704)
(64, 'Ann Arbor', 'Michigan', 42.276251772730504, -83.79533196153221)
(65, 'Sunnyvale', 'California', 37.38605403018868, -122.01669147940767)
(66, 'Lansing', 'Michigan', 42.763501945383965, -84.5608960541933)
(67, 'Cary', 'North Carolina', 35.76226257294572, -78.77756259145124)
(68, 'Columbia', 'Missouri', 38.934650457414016, -92.29671835855945)
(69, 'Mesquite', 'Texas', 32.76687503954722, -96.61232803353901)
(70, 'Metairie', 'Louisiana', 29.984995812152576, -90.16564579561714)
(71, 'Torrance', 'California', 33.82308938589283, -118.31916197449047)
(72, 'Clearwater', 'Florida', 27.978039482302922, -82.78006630860533)
(73, 'Compton', 'California', 33.88488700805826, -118.23822893118933)
(74, 'Inglewood', 'California', 33.988269556108605, -118.37410273442688)
(75, 'Olathe', 'Kansas', 38.89894640198022, -94.8284307387089)
(76, 'Thornton', 'Colorado', 39.92188822500001, -104.96004514462294)
(77, 'Boulder', 'Colorado', 40.04990576494393, -105.19755177178362)
(78, 'Carrollton', 'Texas', 32.9665368431672, -96.88964638023529)
(79, 'Thousand Oaks', 'California', 34.19563460545455, -118.88045067086253)
(80, 'Victorville', 'California', 34.47729336666667, -117.33871779514375)
(81, 'Hamilton', 'Ohio', 39.393149460512156, -84.50424538170161)
(82, 'Pearland', 'Texas', 29.558064790623845, -95.26195838364859)
(83, 'Springfield', 'Illinois', 39.79963791104973, -89.64930121757392)
(84, 'Allentown', 'Pennsylvania', 40.6051146570685, -75.4678261729881)
(85, 'Murrieta', 'California', 33.567828984894824, -117.22282847099396)
(86, 'Joliet', 'Illinois', 41.54701680965355, -88.27692881041217)
(87, 'Norman', 'Oklahoma', 35.22916956372246, -97.31386304181937)
(88, 'Nampa', 'Idaho', 43.60620958414325, -116.61963879565936)
(89, 'Westminster', 'Colorado', 39.856656362135936, -105.04422525713797)
(90, 'Clovis', 'California', 36.82912365915421, -119.69236999843089)
(91, 'Richmond', 'California', 37.93406647080575, -122.37792955569849)
(92, 'Arvada', 'Colorado', 39.795049015686274, -105.08131869074398)
(93, 'Charlottesville', 'Virginia', 38.070214647345274, -78.50371689501613)
(94, 'Tuscaloosa', 'Alabama', 33.194742751950486, -87.56784190568058)
(95, 'El Monte', 'California', 34.075221705559215, -118.04022033886444)
(96, 'Ventura', 'California', 34.28490644791317, -119.28861332294655)
(97, 'Lewisville', 'Texas', 33.01641049779106, -96.9813454037639)
(98, 'West Covina', 'California', 34.06640037218058, -117.9382423692552)
(99, 'Elgin', 'Illinois', 42.03687682350779, -88.26429012172287)
(100, 'Greenville', 'North Carolina', 35.62186453975184, -77.39847207912158)
(101, 'Manassas', 'Virginia', 38.784821823779495, -77.51152028615682)
(102, 'Hillsboro', 'Oregon', 45.49972766348097, -122.94534227350803)
(103, 'Green Bay', 'Wisconsin', 44.486353976457934, -88.02038512047565)
(104, 'Richardson', 'Texas', 32.96523041916345, -96.74558680322752)
(105, 'West Chester', 'Pennsylvania', 39.98353038281101, -75.59546136002155)
(106, 'Norwalk', 'California', 33.90759488308463, -118.08475795155474)
(107, 'Antioch', 'California', 38.002511658928576, -121.8124886882133)
(108, 'Fairfield', 'California', 38.26423879358975, -122.04332101768043)
(109, 'Everett', 'Washington', 47.989954086956494, -122.20208124026493)
(110, 'Erie', 'Pennsylvania', 42.123722349999994, -80.08332664191322)
(111, 'Riverview', 'Florida', 27.855429069443257, -82.31812169383126)
(112, 'Vacaville', 'California', 38.35077894419089, -121.96919492860495)
(113, 'Grand Junction', 'Colorado', 39.077021109123834, -108.54758283682123)
(114, 'Hesperia', 'California', 34.409760625, -117.38725220443564)
(115, 'San Mateo', 'California', 37.56462673402062, -122.32106410258969)
(116, 'Franklin', 'Tennessee', 35.90437546126269, -86.86606658180322)
(117, 'Merced', 'California', 37.31639243051783, -120.45520131412711)
(118, 'Lexington', 'South Carolina', 33.99130487558413, -81.25488264298544)

(119, 'Chapel Hill', 'North Carolina', 35.944320610329264, -79.03800256738151)
(120, 'Rialto', 'California', 34.1151291974359, -117.39435318791276)
(121, 'Columbia', 'Maryland', 39.21138239615816, -76.87965350577723)
(122, 'Meridian', 'Idaho', 43.59069012245927, -116.3883152851739)
(123, 'Lawrence', 'Kansas', 38.96682736099623, -95.23878052268516)
(124, 'Greeley', 'Colorado', 40.41194859375, -104.69730476904851)
(125, 'League City', 'Texas', 29.498070607389014, -95.10865092359022)
(126, 'Mission Viejo', 'California', 33.614618414436414, -117.66557058051434)
(127, 'Livermore', 'California', 37.67517326263379, -121.75509123023458)
(128, 'Portsmouth', 'Virginia', 36.80965797236636, -76.3692236804929)
(129, 'Hawthorne', 'California', 33.92291718197, -118.34873156477205)
(130, 'Johnson City', 'Tennessee', 36.33432894886623, -82.34241039662975)
(131, 'Idaho Falls', 'Idaho', 43.51971125645162, -112.0075389240074)
(132, 'Asheville', 'North Carolina', 35.595068857748934, -82.55510534709673)
(133, 'Annapolis', 'Maryland', 38.984922760015564, -76.51689705332227)
(134, 'Sterling', 'Virginia', 39.00710915577091, -77.3978672790512)
(135, 'Apopka', 'Florida', 28.663085719315802, -81.5055547383544)
(136, 'Medford', 'Oregon', 42.31322278950805, -122.89012099575379)
(137, 'Allen', 'Texas', 33.0965760843764, -96.62895660530828)
(138, 'Plainfield', 'Illinois', 41.65192216681415, -88.21139928465138)
--------No coords found for New Bedford, Massachusetts--------
(140, 'Roswell', 'Georgia', 34.046295925740914, -84.3806711198685)
--------No coords found for Lynn, Massachusetts--------
(142, 'Cleveland', 'Tennessee', 35.15438089569165, -84.8839830829404)
(143, 'Williamsburg', 'Virginia', 37.25602108295043, -76.70716225667314)
(144, 'Lees Summit', 'Missouri', 38.912430161352646, -94.35225886698315)
(145, 'Newnan', 'Georgia', 33.38578629255618, -84.80220236915325)
(146, 'Canton', 'Michigan', 42.32821253053803, -83.47029940886807)
(147, 'Herndon', 'Virginia', 38.9739584027125, -77.37290152103066)
(148, 'Flagstaff', 'Arizona', 35.19631822066271, -111.65654053364986)
(149, 'Chino', 'California', 33.958431489583326, -117.64879801092604)
(150, 'Fort Pierce', 'Florida', 27.42448219014571, -80.43603995299203)
--------No coords found for Fall River, Massachusetts--------
(152, 'Newport Beach', 'California', 33.63221158565527, -117.87749834494784)
(153, 'Waukegan', 'Illinois', 42.35817968665964, -87.86139072518169)
(154, 'Pflugerville', 'Texas', 30.454537382699723, -97.60609868061613)
(155, 'Bloomington', 'Minnesota', 47.92962756666666, -91.80029643333332)
(156, 'Longmont', 'Colorado', 40.170957275286426, -105.10600123167436)
(157, 'Clifton', 'New Jersey', 40.8785913, -74.1539341)
(158, 'Jackson', 'Tennessee', 35.61072465072433, -88.8199495985511)
(159, 'Gresham', 'Oregon', 45.50755095351105, -122.43120980697458)
(160, 'Troy', 'Michigan', 42.55438811430853, -83.11681967204541)
(161, 'Kingsport', 'Tennessee', 36.54455426663845, -82.56829232763076)
--------No coords found for Quincy, Massachusetts--------
(163, 'Ogden', 'Utah', 41.209867303183245, -112.0167139440653)
(164, 'Stafford', 'Virginia', 38.44436228178189, -77.40852491247965)
(165, 'Manteca', 'California', 37.80804515759494, -121.21292400514878)
(166, 'Camarillo', 'California', 34.225576212000014, -119.05701489462108)
(167, 'Farmington Hills', 'Michigan', 42.51044348475779, -83.40973868909383)
(168, 'Apple Valley', 'California', 34.50609796944445, -117.25598031541064)
(169, 'Oviedo', 'Florida', 28.64616286616934, -81.2185561578941)
(170, 'Mount Pleasant', 'South Carolina', 32.81579078186367, -79.85585614376963)
(171, 'Covina', 'California', 34.095163825494346, -117.91160773681565)
(172, 'Upland', 'California', 34.1340677745923, -117.66250216537274)
(173, 'Deltona', 'Florida', 28.902938234770044, -81.24555317393373)
(174, 'Carson', 'California', 33.847231342774556, -118.26827592466333)
(175, 'Lancaster Township', 'Pennsylvania', 40.072691404431104, -76.32296697248154)
(176, 'Brooklyn Park', 'Minnesota', 45.963161708571434, -93.15675823142855)
(177, 'Mountain View', 'California', 37.38161873237541, -122.08163492865512)
(178, 'Apex', 'North Carolina', 35.72862304629829, -78.8888094846593)
(179, 'Missouri City', 'Texas', 29.52751200991949, -95.54161310084233)
(180, 'Richmond', 'Texas', 29.652707169907398, -95.75556178831667)
(181, 'Pasco', 'Washington', 46.24863676865381, -119.12908336723291)
(182, 'Casa Grande', 'Arizona', 32.89568831607143, -111.73370114848082)
(183, 'San Ramon', 'California', 37.7612636455003, -121.90218467171705)
(184, 'Town of Poughkeepsie', 'New York', 41.702100897622195, -73.91884753468925)
(185, 'Bethlehem', 'Pennsylvania', 40.59818919198947, -75.37366920939247)
(186, 'Brandon', 'Mississippi', 32.26966132792986, -89.96975077127198)
(187, 'Lake Forest', 'California', 33.64125739973855, -117.69058268756127)
(188, 'New Rochelle', 'New York', 40.916378656022886, -73.78648976446075)
(189, 'Palm Harbor', 'Florida', 28.079742976073664, -82.7601012511632)
(190, 'Southfield', 'Michigan', 42.457776821323534, -83.28198399788613)
(191, 'Mooresville', 'North Carolina', 35.57891526799253, -80.80569904891301)
(192, 'Chino Hills', 'California', 33.98065249736373, -117.72684756078218)
--------No coords found for Brick Township, New Jersey--------
(194, 'Lake Elsinore', 'California', 33.66609939567599, -117.35655740886733)
(195, 'Suwanee', 'Georgia', 34.06323270515614, -84.09076224471265)
(196, 'Glen Allen', 'Virginia', 37.68473913422227, -77.56159984715174)
(197, 'Flower Mound', 'Texas', 33.02355723233286, -97.09771836560745)
(198, 'Waterford', 'Michigan', 42.642238636504366, -83.41041966641683)
(199, 'Columbus', 'Indiana', 39.17980386420454, -85.96638373208795)
(200, 'West Lafayette', 'Indiana', 40.454831040780284, -86.92666438030413)
(201, 'Yorba Linda', 'California', 33.889431082822284, -117.79155222102334)
(202, 'Layton', 'Utah', 41.08648453368684, -111.92926501579048)
(203, 'Bolingbrook', 'Illinois', 41.705721952126645, -88.07391640150287)
(204, 'Ypsilanti', 'Michigan', 42.22590772059032, -83.63338861326189)
(205, 'Saint Cloud', 'Florida', 28.249993304446008, -81.2960213038654)
(206, 'Palm Beach Gardens', 'Florida', 26.842552795424137, -80.08621417035737)
(207, 'Alameda', 'California', 37.770288216331494, -122.25685414283417)
(208, 'Venice', 'Florida', 27.153907241330007, -82.73857611989568)
(209, 'Cocoa', 'Florida', 28.364878660512833, -80.74113602998669)
(210, 'Palo Alto', 'California', 37.44225110221239, -122.15798043938169)
(211, 'Salisbury', 'Maryland', 38.3701470619992, -75.61811385447686)
(212, 'Milton', 'Florida', 30.670031718912355, -87.05887692642695)
(213, 'Grants Pass', 'Oregon', 42.45384501094588, -123.3298158835657)
(214, 'Kenner', 'Louisiana', 29.993788991200486, -90.24533050144221)
(215, 'Maple Grove', 'Minnesota', 45.1083543522906, -93.48671655364865)
(216, 'Corvallis', 'Oregon', 44.58888938825484, -123.28455313282548)
(217, 'The Villages', 'Florida', 28.9209822, -81.99453467969492)
(218, 'Orland Park', 'Illinois', 41.62352610107136, -87.8338909444633)
(219, 'San Luis Obispo', 'California', 35.25722642653147, -120.6472192685223)
(220, 'North Richland Hills', 'Texas', 32.85857017808006, -97.2170276057323)
(221, 'Ewa Beach', 'Hawaii', 21.32462850686522, -158.01696109960474)

In [10]:
# Create a dataframe of locations with no coordinates, to see how many we're losing from our dataset
bad_coords_df = pd.DataFrame(bad_coords, columns=["RegionID", "City", "State", "Zip Code"])
bad_coords_df

    RegionID                 City           State  Zip Code
0      11722           Greensboro  North Carolina     27395
1      17759           Des Moines            Iowa     50307
2      33058          New Bedford   Massachusetts      2740
3      39558                 Lynn   Massachusetts      1901
4      31525           Fall River   Massachusetts      2720
..       ...                  ...             ...       ...
92     44095  Bedminster Township      New Jersey      7921
93     44310           Brigantine      New Jersey      8203
94     37950         Cold Springs          Nevada     89067
95     27950             Wildwood      New Jersey      8260
96     50339        Sea Isle City      New Jersey      8243

[97 rows x 4 columns]

In [11]:
# create dataframe from viable locations
zip_coords_df_cleaned = pd.DataFrame(zipcodes_coords_dict, columns=['RegionID', 'City', 'State', 'Zip Code', 'Latitude', 'Longitude'])
zip_coords_df_cleaned

     RegionID           City         State  Zip Code   Latitude   Longitude
0        6181       New York      New York     10001  40.748418  -73.994147
1       17426        Chicago      Illinois     60601  41.885910  -87.623849
2       18959      Las Vegas        Nevada     89101  36.167540 -115.139739
3       38128         Dallas         Texas     75201  32.785918  -96.798987
4       10920       Columbus          Ohio     43085  40.099379  -83.015356
..        ...            ...           ...       ...        ...         ...
933     25643   Longboat Key       Florida     34228  27.392012  -82.641345
934     49592       New Hope  Pennsylvania     18938  40.348777  -74.994791
935     48710         Arnold    California     95223  38.257253 -120.328708
936     12306      Langhorne  Pennsylvania     19047  40.178802  -74.913333
937     33433  Pingree Grove      Illinois     60081  42.440309  -88.217048

[938 rows x 6 columns]

In [6]:
# Export zip_coords_df to CSV, which will serve as our finalized dictionary of location data to unique RegionID
#zip_coords_df_cleaned.to_csv("./resources/zipcodes_coordinates.csv", index=False)