In [37]:
import pandas as pd
import os
import csv
from pathlib import Path
import datetime as dt
from uszipcode import SearchEngine

In [38]:
file_to_load = "./resources_mhardy/Sale_Prices_City.csv/Sale_Prices_City_2011.csv"
sale_price_df = pd.read_csv(file_to_load, low_memory=False)
sale_price_df

,Unnamed: 0,RegionID,RegionName,StateName,SizeRank,2011-01,2011-02,2011-03,2011-04,2011-05,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,0,6181,New York,New York,1,462700.0,466200.0,465600.0,469500.0,471300.0,...,563200.0,570500.0,572800.0,569900.0,560800.0,571500.0,575100.0,571700.0,568300.0,573600.0
1,1,12447,Los Angeles,California,2,350300.0,353000.0,344300.0,347400.0,342900.0,...,706800.0,711800.0,717300.0,714100.0,711900.0,718400.0,727100.0,738200.0,760200.0,NaN
2,2,39051,Houston,Texas,3,139700.0,138100.0,133200.0,131100.0,129900.0,...,209700.0,207400.0,207600.0,207000.0,211400.0,211500.0,217700.0,219200.0,223800.0,NaN
3,3,17426,Chicago,Illinois,4,188500.0,189400.0,186300.0,177700.0,167900.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
4,4,6915,San Antonio,Texas,5,135800.0,131600.0,130700.0,129000.0,130900.0,...,197100.0,198700.0,200200.0,200800.0,203400.0,203800.0,205400.0,205400.0,208300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723,3723,40400,Port Bolivar,Texas,3724,NaN,NaN,NaN,NaN,NaN,...,278400.0,254300.0,273200.0,286200.0,278100.0,285500.0,267200.0,302900.0,333700.0,330100.0
3724,3724,397820,Long Beach Township,New Jersey,3725,NaN,NaN,NaN,NaN,NaN,...,846300.0,912100.0,943700.0,897600.0,836000.0,839900.0,824100.0,839000.0,860600.0,NaN
3725,3725,37346,Beech Mountain,North Carolina,3726,NaN,NaN,NaN,NaN,NaN,...,191400.0,172700.0,195700.0,189500.0,166500.0,130900.0,139800.0,129400.0,124800.0,131000.0
3726,3726,34991,Corolla,North Carolina,3727,NaN,NaN,NaN,NaN,NaN,...,522400.0,521000.0,480000.0,430600.0,476400.0,560800.0,565400.0,514000.0,444200.0,NaN
3727,3727,52829,La Vernia,Texas,3728,NaN,NaN,NaN,NaN,NaN,...,337900.0,342900.0,358300.0,373100.0,375100.0,358600.0,356500.0,336700.0,340400.0,327000.0

In [39]:
clean_sale_df = sale_price_df.dropna()
clean_sale_df = clean_sale_df.drop(columns=['Unnamed: 0'], axis=1)
clean_sale_df

,RegionID,RegionName,StateName,SizeRank,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,6181,New York,New York,1,462700.0,466200.0,465600.0,469500.0,471300.0,468600.0,...,563200.0,570500.0,572800.0,569900.0,560800.0,571500.0,575100.0,571700.0,568300.0,573600.0
3,17426,Chicago,Illinois,4,188500.0,189400.0,186300.0,177700.0,167900.0,174700.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
7,18959,Las Vegas,Nevada,8,115600.0,114000.0,110800.0,109600.0,108200.0,107500.0,...,266000.0,268200.0,268400.0,270400.0,272200.0,274400.0,277500.0,278900.0,283000.0,284700.0
9,38128,Dallas,Texas,10,191900.0,184500.0,174500.0,152000.0,162900.0,171400.0,...,300600.0,301100.0,301500.0,310100.0,314600.0,316900.0,307100.0,321500.0,315500.0,321700.0
18,10920,Columbus,Ohio,19,89100.0,86000.0,79800.0,79300.0,78600.0,82300.0,...,152600.0,154800.0,158500.0,157700.0,162900.0,166600.0,172700.0,175300.0,173600.0,177600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3703,48710,Arnold,California,3704,266300.0,244200.0,217800.0,191200.0,201500.0,208400.0,...,326500.0,317800.0,293100.0,281000.0,279100.0,279400.0,287100.0,305300.0,325600.0,345100.0
3713,12306,Langhorne,Pennsylvania,3714,272300.0,291500.0,305600.0,342300.0,342600.0,329400.0,...,339800.0,371300.0,358600.0,366800.0,362400.0,396600.0,398200.0,404100.0,397100.0,416200.0
3715,33433,Pingree Grove,Illinois,3716,203600.0,175600.0,170200.0,184800.0,198900.0,191800.0,...,206200.0,198200.0,214700.0,211800.0,217500.0,250200.0,270300.0,260200.0,224300.0,216600.0
3717,32133,Idyllwild,California,3718,182900.0,225000.0,230500.0,240100.0,182500.0,183700.0,...,313500.0,309100.0,322400.0,321300.0,342400.0,330500.0,353800.0,355500.0,389300.0,360100.0
3721,50339,Sea Isle City,New Jersey,3722,500500.0,538200.0,543800.0,533600.0,552300.0,536300.0,...,718400.0,743300.0,762300.0,820300.0,783400.0,789700.0,776600.0,811700.0,815700.0,795900.0

In [40]:
# export csv
# file_path = Path("./resources_mhardy/Sale_Prices_City.csv/Sale_Prices_City_sample.csv")
# clean_sale_df.to_csv(file_path, index=False)

In [41]:
# getting ready to transpose data so its indexed by timeframe
# first, drop useless columns
time_df = clean_sale_df.drop(columns=["RegionName", "StateName", "SizeRank"])
time_df

,RegionID,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,6181,462700.0,466200.0,465600.0,469500.0,471300.0,468600.0,469500.0,470800.0,476700.0,...,563200.0,570500.0,572800.0,569900.0,560800.0,571500.0,575100.0,571700.0,568300.0,573600.0
3,17426,188500.0,189400.0,186300.0,177700.0,167900.0,174700.0,182900.0,189300.0,190000.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
7,18959,115600.0,114000.0,110800.0,109600.0,108200.0,107500.0,105500.0,102700.0,102200.0,...,266000.0,268200.0,268400.0,270400.0,272200.0,274400.0,277500.0,278900.0,283000.0,284700.0
9,38128,191900.0,184500.0,174500.0,152000.0,162900.0,171400.0,177500.0,179200.0,178100.0,...,300600.0,301100.0,301500.0,310100.0,314600.0,316900.0,307100.0,321500.0,315500.0,321700.0
18,10920,89100.0,86000.0,79800.0,79300.0,78600.0,82300.0,84200.0,87600.0,87500.0,...,152600.0,154800.0,158500.0,157700.0,162900.0,166600.0,172700.0,175300.0,173600.0,177600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3703,48710,266300.0,244200.0,217800.0,191200.0,201500.0,208400.0,208600.0,200800.0,211900.0,...,326500.0,317800.0,293100.0,281000.0,279100.0,279400.0,287100.0,305300.0,325600.0,345100.0
3713,12306,272300.0,291500.0,305600.0,342300.0,342600.0,329400.0,297500.0,279400.0,294300.0,...,339800.0,371300.0,358600.0,366800.0,362400.0,396600.0,398200.0,404100.0,397100.0,416200.0
3715,33433,203600.0,175600.0,170200.0,184800.0,198900.0,191800.0,176300.0,145700.0,149500.0,...,206200.0,198200.0,214700.0,211800.0,217500.0,250200.0,270300.0,260200.0,224300.0,216600.0
3717,32133,182900.0,225000.0,230500.0,240100.0,182500.0,183700.0,171300.0,174400.0,166400.0,...,313500.0,309100.0,322400.0,321300.0,342400.0,330500.0,353800.0,355500.0,389300.0,360100.0
3721,50339,500500.0,538200.0,543800.0,533600.0,552300.0,536300.0,559600.0,565400.0,566000.0,...,718400.0,743300.0,762300.0,820300.0,783400.0,789700.0,776600.0,811700.0,815700.0,795900.0

In [42]:

time_transposed = time_df.transpose()
time_transposed.reset_index(drop = False, inplace = True)
time_transposed = time_transposed.rename(columns=time_transposed.iloc[0])
time_transposed = time_transposed.drop([0, 0])
time_transposed = time_transposed.rename(columns={"RegionID": 'DATE'})
time_transposed

,DATE,6181.0,17426.0,18959.0,38128.0,10920.0,12455.0,13121.0,11093.0,41568.0,...,41536.0,47409.0,21021.0,25643.0,49592.0,48710.0,12306.0,33433.0,32133.0,50339.0
1,2011-01,462700.0,188500.0,115600.0,191900.0,89100.0,125900.0,82000.0,201400.0,401100.0,...,237800.0,128400.0,204100.0,432300.0,528100.0,266300.0,272300.0,203600.0,182900.0,500500.0
2,2011-02,466200.0,189400.0,114000.0,184500.0,86000.0,124000.0,82800.0,205300.0,386000.0,...,216000.0,148400.0,194000.0,476900.0,482600.0,244200.0,291500.0,175600.0,225000.0,538200.0
3,2011-03,465600.0,186300.0,110800.0,174500.0,79800.0,118300.0,85500.0,198800.0,376200.0,...,208800.0,150500.0,192400.0,440900.0,454800.0,217800.0,305600.0,170200.0,230500.0,543800.0
4,2011-04,469500.0,177700.0,109600.0,152000.0,79300.0,117600.0,87800.0,198500.0,362800.0,...,229800.0,161600.0,185900.0,457500.0,463300.0,191200.0,342300.0,184800.0,240100.0,533600.0
5,2011-05,471300.0,167900.0,108200.0,162900.0,78600.0,113800.0,88800.0,190900.0,370300.0,...,260100.0,131500.0,175900.0,470600.0,475400.0,201500.0,342600.0,198900.0,182500.0,552300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2019-11,571500.0,264300.0,274400.0,316900.0,166600.0,174600.0,247400.0,445400.0,566400.0,...,402700.0,343700.0,297200.0,557900.0,530300.0,279400.0,396600.0,250200.0,330500.0,789700.0
108,2019-12,575100.0,270000.0,277500.0,307100.0,172700.0,176600.0,251100.0,435500.0,577600.0,...,454400.0,321500.0,292100.0,577100.0,579600.0,287100.0,398200.0,270300.0,353800.0,776600.0
109,2020-01,571700.0,281400.0,278900.0,321500.0,175300.0,170800.0,254800.0,435100.0,580100.0,...,499200.0,273700.0,275100.0,557900.0,539400.0,305300.0,404100.0,260200.0,355500.0,811700.0
110,2020-02,568300.0,302900.0,283000.0,315500.0,173600.0,173100.0,263500.0,436900.0,575700.0,...,513400.0,314400.0,265400.0,565600.0,609700.0,325600.0,397100.0,224300.0,389300.0,815700.0
111,2020-03,573600.0,309200.0,284700.0,321700.0,177600.0,176200.0,270500.0,442700.0,586100.0,...,487200.0,319400.0,269300.0,579700.0,608700.0,345100.0,416200.0,216600.0,360100.0,795900.0

In [43]:
# convert month column to datetime format
time_transposed['DATE'] = pd.to_datetime(time_transposed['DATE'], infer_datetime_format=True)
time_transposed.dtypes

DATE       datetime64[ns]
6181.0            float64
17426.0           float64
18959.0           float64
38128.0           float64
                ...
48710.0           float64
12306.0           float64
33433.0           float64
32133.0           float64
50339.0           float64
Length: 1098, dtype: object

In [44]:
time_transposed

,DATE,6181.0,17426.0,18959.0,38128.0,10920.0,12455.0,13121.0,11093.0,41568.0,...,41536.0,47409.0,21021.0,25643.0,49592.0,48710.0,12306.0,33433.0,32133.0,50339.0
1,2011-01-01,462700.0,188500.0,115600.0,191900.0,89100.0,125900.0,82000.0,201400.0,401100.0,...,237800.0,128400.0,204100.0,432300.0,528100.0,266300.0,272300.0,203600.0,182900.0,500500.0
2,2011-02-01,466200.0,189400.0,114000.0,184500.0,86000.0,124000.0,82800.0,205300.0,386000.0,...,216000.0,148400.0,194000.0,476900.0,482600.0,244200.0,291500.0,175600.0,225000.0,538200.0
3,2011-03-01,465600.0,186300.0,110800.0,174500.0,79800.0,118300.0,85500.0,198800.0,376200.0,...,208800.0,150500.0,192400.0,440900.0,454800.0,217800.0,305600.0,170200.0,230500.0,543800.0
4,2011-04-01,469500.0,177700.0,109600.0,152000.0,79300.0,117600.0,87800.0,198500.0,362800.0,...,229800.0,161600.0,185900.0,457500.0,463300.0,191200.0,342300.0,184800.0,240100.0,533600.0
5,2011-05-01,471300.0,167900.0,108200.0,162900.0,78600.0,113800.0,88800.0,190900.0,370300.0,...,260100.0,131500.0,175900.0,470600.0,475400.0,201500.0,342600.0,198900.0,182500.0,552300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2019-11-01,571500.0,264300.0,274400.0,316900.0,166600.0,174600.0,247400.0,445400.0,566400.0,...,402700.0,343700.0,297200.0,557900.0,530300.0,279400.0,396600.0,250200.0,330500.0,789700.0
108,2019-12-01,575100.0,270000.0,277500.0,307100.0,172700.0,176600.0,251100.0,435500.0,577600.0,...,454400.0,321500.0,292100.0,577100.0,579600.0,287100.0,398200.0,270300.0,353800.0,776600.0
109,2020-01-01,571700.0,281400.0,278900.0,321500.0,175300.0,170800.0,254800.0,435100.0,580100.0,...,499200.0,273700.0,275100.0,557900.0,539400.0,305300.0,404100.0,260200.0,355500.0,811700.0
110,2020-02-01,568300.0,302900.0,283000.0,315500.0,173600.0,173100.0,263500.0,436900.0,575700.0,...,513400.0,314400.0,265400.0,565600.0,609700.0,325600.0,397100.0,224300.0,389300.0,815700.0
111,2020-03-01,573600.0,309200.0,284700.0,321700.0,177600.0,176200.0,270500.0,442700.0,586100.0,...,487200.0,319400.0,269300.0,579700.0,608700.0,345100.0,416200.0,216600.0,360100.0,795900.0

In [45]:
file_path = Path("./resources_mhardy/Sale_Prices_City.csv/time_df_transposed.csv")
time_transposed.to_csv(file_path, index=False)

In [46]:
# start transforming inflation data
# start by loading in the file
file_path = Path("./resources_mhardy/CPIAUCNS/CPIAUCNS.csv")
cpi_df = pd.read_csv(file_path)
cpi_df

            DATE  CPIAUCNS
0     1913-01-01     9.800
1     1913-02-01     9.800
2     1913-03-01     9.800
3     1913-04-01     9.800
4     1913-05-01     9.700
...          ...       ...
1304  2021-09-01   274.310
1305  2021-10-01   276.589
1306  2021-11-01   277.948
1307  2021-12-01   278.802
1308  2022-01-01   281.148

[1309 rows x 2 columns]

In [47]:
cpi_df['DATE'] = pd.to_datetime(cpi_df['DATE'], infer_datetime_format=True)
cpi_df.dtypes

DATE        datetime64[ns]
CPIAUCNS           float64
dtype: object

In [48]:
file_path = Path("./resources_mhardy/Sale_Prices_City.csv/cpi_datetime.csv")
cpi_df.to_csv(file_path, index=False)

In [51]:
time_transposed

,DATE,6181.0,17426.0,18959.0,38128.0,10920.0,12455.0,13121.0,11093.0,41568.0,...,41536.0,47409.0,21021.0,25643.0,49592.0,48710.0,12306.0,33433.0,32133.0,50339.0
1,2011-01-01,462700.0,188500.0,115600.0,191900.0,89100.0,125900.0,82000.0,201400.0,401100.0,...,237800.0,128400.0,204100.0,432300.0,528100.0,266300.0,272300.0,203600.0,182900.0,500500.0
2,2011-02-01,466200.0,189400.0,114000.0,184500.0,86000.0,124000.0,82800.0,205300.0,386000.0,...,216000.0,148400.0,194000.0,476900.0,482600.0,244200.0,291500.0,175600.0,225000.0,538200.0
3,2011-03-01,465600.0,186300.0,110800.0,174500.0,79800.0,118300.0,85500.0,198800.0,376200.0,...,208800.0,150500.0,192400.0,440900.0,454800.0,217800.0,305600.0,170200.0,230500.0,543800.0
4,2011-04-01,469500.0,177700.0,109600.0,152000.0,79300.0,117600.0,87800.0,198500.0,362800.0,...,229800.0,161600.0,185900.0,457500.0,463300.0,191200.0,342300.0,184800.0,240100.0,533600.0
5,2011-05-01,471300.0,167900.0,108200.0,162900.0,78600.0,113800.0,88800.0,190900.0,370300.0,...,260100.0,131500.0,175900.0,470600.0,475400.0,201500.0,342600.0,198900.0,182500.0,552300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2019-11-01,571500.0,264300.0,274400.0,316900.0,166600.0,174600.0,247400.0,445400.0,566400.0,...,402700.0,343700.0,297200.0,557900.0,530300.0,279400.0,396600.0,250200.0,330500.0,789700.0
108,2019-12-01,575100.0,270000.0,277500.0,307100.0,172700.0,176600.0,251100.0,435500.0,577600.0,...,454400.0,321500.0,292100.0,577100.0,579600.0,287100.0,398200.0,270300.0,353800.0,776600.0
109,2020-01-01,571700.0,281400.0,278900.0,321500.0,175300.0,170800.0,254800.0,435100.0,580100.0,...,499200.0,273700.0,275100.0,557900.0,539400.0,305300.0,404100.0,260200.0,355500.0,811700.0
110,2020-02-01,568300.0,302900.0,283000.0,315500.0,173600.0,173100.0,263500.0,436900.0,575700.0,...,513400.0,314400.0,265400.0,565600.0,609700.0,325600.0,397100.0,224300.0,389300.0,815700.0
111,2020-03-01,573600.0,309200.0,284700.0,321700.0,177600.0,176200.0,270500.0,442700.0,586100.0,...,487200.0,319400.0,269300.0,579700.0,608700.0,345100.0,416200.0,216600.0,360100.0,795900.0

In [52]:
# build uszipcode engine to assign zipcodes to cities

engine = SearchEngine()
zipcodes = engine.by_city_and_state(city="Los Angeles", state="california")
for zipcode in zipcodes:
    print(zipcode.zipcode, zipcode.major_city, zipcode.population)

ValueError: Can only compare identically-labeled Series objects